/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncomendaTokenRouteImport } from './routes/encomenda.$token'
import { Route as AuthenticatedEquipaRouteImport } from './routes/_authenticated/equipa'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedNegocioIndexRouteImport } from './routes/_authenticated/negocio/index'
import { Route as AuthenticatedCasaIndexRouteImport } from './routes/_authenticated/casa/index'
import { Route as AuthenticatedNegocioVendasRouteImport } from './routes/_authenticated/negocio/vendas'
import { Route as AuthenticatedNegocioStockRouteImport } from './routes/_authenticated/negocio/stock'
import { Route as AuthenticatedNegocioRelatoriosRouteImport } from './routes/_authenticated/negocio/relatorios'
import { Route as AuthenticatedNegocioEncomendasRouteImport } from './routes/_authenticated/negocio/encomendas'
import { Route as AuthenticatedNegocioDespesasRouteImport } from './routes/_authenticated/negocio/despesas'
import { Route as AuthenticatedNegocioClientesRouteImport } from './routes/_authenticated/negocio/clientes'
import { Route as AuthenticatedNegocioAprovacoesRouteImport } from './routes/_authenticated/negocio/aprovacoes'
import { Route as AuthenticatedNegocioAgendaRouteImport } from './routes/_authenticated/negocio/agenda'
import { Route as AuthenticatedCasaStockRouteImport } from './routes/_authenticated/casa/stock'
import { Route as AuthenticatedCasaScannerRouteImport } from './routes/_authenticated/casa/scanner'
import { Route as AuthenticatedCasaRelatoriosRouteImport } from './routes/_authenticated/casa/relatorios'
import { Route as AuthenticatedCasaReceitasRouteImport } from './routes/_authenticated/casa/receitas'
import { Route as AuthenticatedCasaListaComprasRouteImport } from './routes/_authenticated/casa/lista-compras'
import { Route as AuthenticatedCasaDespesasRouteImport } from './routes/_authenticated/casa/despesas'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendaTokenRoute = EncomendaTokenRouteImport.update({
  id: '/encomenda/$token',
  path: '/encomenda/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipaRoute = AuthenticatedEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNegocioIndexRoute =
  AuthenticatedNegocioIndexRouteImport.update({
    id: '/negocio/',
    path: '/negocio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaIndexRoute = AuthenticatedCasaIndexRouteImport.update({
  id: '/casa/',
  path: '/casa/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegocioVendasRoute =
  AuthenticatedNegocioVendasRouteImport.update({
    id: '/negocio/vendas',
    path: '/negocio/vendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioStockRoute =
  AuthenticatedNegocioStockRouteImport.update({
    id: '/negocio/stock',
    path: '/negocio/stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioRelatoriosRoute =
  AuthenticatedNegocioRelatoriosRouteImport.update({
    id: '/negocio/relatorios',
    path: '/negocio/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioEncomendasRoute =
  AuthenticatedNegocioEncomendasRouteImport.update({
    id: '/negocio/encomendas',
    path: '/negocio/encomendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioDespesasRoute =
  AuthenticatedNegocioDespesasRouteImport.update({
    id: '/negocio/despesas',
    path: '/negocio/despesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioClientesRoute =
  AuthenticatedNegocioClientesRouteImport.update({
    id: '/negocio/clientes',
    path: '/negocio/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioAprovacoesRoute =
  AuthenticatedNegocioAprovacoesRouteImport.update({
    id: '/negocio/aprovacoes',
    path: '/negocio/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioAgendaRoute =
  AuthenticatedNegocioAgendaRouteImport.update({
    id: '/negocio/agenda',
    path: '/negocio/agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaStockRoute = AuthenticatedCasaStockRouteImport.update({
  id: '/casa/stock',
  path: '/casa/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasaScannerRoute =
  AuthenticatedCasaScannerRouteImport.update({
    id: '/casa/scanner',
    path: '/casa/scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaRelatoriosRoute =
  AuthenticatedCasaRelatoriosRouteImport.update({
    id: '/casa/relatorios',
    path: '/casa/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaReceitasRoute =
  AuthenticatedCasaReceitasRouteImport.update({
    id: '/casa/receitas',
    path: '/casa/receitas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaListaComprasRoute =
  AuthenticatedCasaListaComprasRouteImport.update({
    id: '/casa/lista-compras',
    path: '/casa/lista-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaDespesasRoute =
  AuthenticatedCasaDespesasRouteImport.update({
    id: '/casa/despesas',
    path: '/casa/despesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/encomenda/$token': typeof EncomendaTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/casa/despesas': typeof AuthenticatedCasaDespesasRoute
  '/casa/lista-compras': typeof AuthenticatedCasaListaComprasRoute
  '/casa/receitas': typeof AuthenticatedCasaReceitasRoute
  '/casa/relatorios': typeof AuthenticatedCasaRelatoriosRoute
  '/casa/scanner': typeof AuthenticatedCasaScannerRoute
  '/casa/stock': typeof AuthenticatedCasaStockRoute
  '/negocio/agenda': typeof AuthenticatedNegocioAgendaRoute
  '/negocio/aprovacoes': typeof AuthenticatedNegocioAprovacoesRoute
  '/negocio/clientes': typeof AuthenticatedNegocioClientesRoute
  '/negocio/despesas': typeof AuthenticatedNegocioDespesasRoute
  '/negocio/encomendas': typeof AuthenticatedNegocioEncomendasRoute
  '/negocio/relatorios': typeof AuthenticatedNegocioRelatoriosRoute
  '/negocio/stock': typeof AuthenticatedNegocioStockRoute
  '/negocio/vendas': typeof AuthenticatedNegocioVendasRoute
  '/casa/': typeof AuthenticatedCasaIndexRoute
  '/negocio/': typeof AuthenticatedNegocioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/encomenda/$token': typeof EncomendaTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/casa/despesas': typeof AuthenticatedCasaDespesasRoute
  '/casa/lista-compras': typeof AuthenticatedCasaListaComprasRoute
  '/casa/receitas': typeof AuthenticatedCasaReceitasRoute
  '/casa/relatorios': typeof AuthenticatedCasaRelatoriosRoute
  '/casa/scanner': typeof AuthenticatedCasaScannerRoute
  '/casa/stock': typeof AuthenticatedCasaStockRoute
  '/negocio/agenda': typeof AuthenticatedNegocioAgendaRoute
  '/negocio/aprovacoes': typeof AuthenticatedNegocioAprovacoesRoute
  '/negocio/clientes': typeof AuthenticatedNegocioClientesRoute
  '/negocio/despesas': typeof AuthenticatedNegocioDespesasRoute
  '/negocio/encomendas': typeof AuthenticatedNegocioEncomendasRoute
  '/negocio/relatorios': typeof AuthenticatedNegocioRelatoriosRoute
  '/negocio/stock': typeof AuthenticatedNegocioStockRoute
  '/negocio/vendas': typeof AuthenticatedNegocioVendasRoute
  '/casa': typeof AuthenticatedCasaIndexRoute
  '/negocio': typeof AuthenticatedNegocioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/equipa': typeof AuthenticatedEquipaRoute
  '/encomenda/$token': typeof EncomendaTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/casa/despesas': typeof AuthenticatedCasaDespesasRoute
  '/_authenticated/casa/lista-compras': typeof AuthenticatedCasaListaComprasRoute
  '/_authenticated/casa/receitas': typeof AuthenticatedCasaReceitasRoute
  '/_authenticated/casa/relatorios': typeof AuthenticatedCasaRelatoriosRoute
  '/_authenticated/casa/scanner': typeof AuthenticatedCasaScannerRoute
  '/_authenticated/casa/stock': typeof AuthenticatedCasaStockRoute
  '/_authenticated/negocio/agenda': typeof AuthenticatedNegocioAgendaRoute
  '/_authenticated/negocio/aprovacoes': typeof AuthenticatedNegocioAprovacoesRoute
  '/_authenticated/negocio/clientes': typeof AuthenticatedNegocioClientesRoute
  '/_authenticated/negocio/despesas': typeof AuthenticatedNegocioDespesasRoute
  '/_authenticated/negocio/encomendas': typeof AuthenticatedNegocioEncomendasRoute
  '/_authenticated/negocio/relatorios': typeof AuthenticatedNegocioRelatoriosRoute
  '/_authenticated/negocio/stock': typeof AuthenticatedNegocioStockRoute
  '/_authenticated/negocio/vendas': typeof AuthenticatedNegocioVendasRoute
  '/_authenticated/casa/': typeof AuthenticatedCasaIndexRoute
  '/_authenticated/negocio/': typeof AuthenticatedNegocioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/equipa'
    | '/encomenda/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/casa/despesas'
    | '/casa/lista-compras'
    | '/casa/receitas'
    | '/casa/relatorios'
    | '/casa/scanner'
    | '/casa/stock'
    | '/negocio/agenda'
    | '/negocio/aprovacoes'
    | '/negocio/clientes'
    | '/negocio/despesas'
    | '/negocio/encomendas'
    | '/negocio/relatorios'
    | '/negocio/stock'
    | '/negocio/vendas'
    | '/casa/'
    | '/negocio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/equipa'
    | '/encomenda/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/casa/despesas'
    | '/casa/lista-compras'
    | '/casa/receitas'
    | '/casa/relatorios'
    | '/casa/scanner'
    | '/casa/stock'
    | '/negocio/agenda'
    | '/negocio/aprovacoes'
    | '/negocio/clientes'
    | '/negocio/despesas'
    | '/negocio/encomendas'
    | '/negocio/relatorios'
    | '/negocio/stock'
    | '/negocio/vendas'
    | '/casa'
    | '/negocio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/equipa'
    | '/encomenda/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/casa/despesas'
    | '/_authenticated/casa/lista-compras'
    | '/_authenticated/casa/receitas'
    | '/_authenticated/casa/relatorios'
    | '/_authenticated/casa/scanner'
    | '/_authenticated/casa/stock'
    | '/_authenticated/negocio/agenda'
    | '/_authenticated/negocio/aprovacoes'
    | '/_authenticated/negocio/clientes'
    | '/_authenticated/negocio/despesas'
    | '/_authenticated/negocio/encomendas'
    | '/_authenticated/negocio/relatorios'
    | '/_authenticated/negocio/stock'
    | '/_authenticated/negocio/vendas'
    | '/_authenticated/casa/'
    | '/_authenticated/negocio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EncomendaTokenRoute: typeof EncomendaTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomenda/$token': {
      id: '/encomenda/$token'
      path: '/encomenda/$token'
      fullPath: '/encomenda/$token'
      preLoaderRoute: typeof EncomendaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipa': {
      id: '/_authenticated/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AuthenticatedEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/negocio/': {
      id: '/_authenticated/negocio/'
      path: '/negocio'
      fullPath: '/negocio/'
      preLoaderRoute: typeof AuthenticatedNegocioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/': {
      id: '/_authenticated/casa/'
      path: '/casa'
      fullPath: '/casa/'
      preLoaderRoute: typeof AuthenticatedCasaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/vendas': {
      id: '/_authenticated/negocio/vendas'
      path: '/negocio/vendas'
      fullPath: '/negocio/vendas'
      preLoaderRoute: typeof AuthenticatedNegocioVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/stock': {
      id: '/_authenticated/negocio/stock'
      path: '/negocio/stock'
      fullPath: '/negocio/stock'
      preLoaderRoute: typeof AuthenticatedNegocioStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/relatorios': {
      id: '/_authenticated/negocio/relatorios'
      path: '/negocio/relatorios'
      fullPath: '/negocio/relatorios'
      preLoaderRoute: typeof AuthenticatedNegocioRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/encomendas': {
      id: '/_authenticated/negocio/encomendas'
      path: '/negocio/encomendas'
      fullPath: '/negocio/encomendas'
      preLoaderRoute: typeof AuthenticatedNegocioEncomendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/despesas': {
      id: '/_authenticated/negocio/despesas'
      path: '/negocio/despesas'
      fullPath: '/negocio/despesas'
      preLoaderRoute: typeof AuthenticatedNegocioDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/clientes': {
      id: '/_authenticated/negocio/clientes'
      path: '/negocio/clientes'
      fullPath: '/negocio/clientes'
      preLoaderRoute: typeof AuthenticatedNegocioClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/aprovacoes': {
      id: '/_authenticated/negocio/aprovacoes'
      path: '/negocio/aprovacoes'
      fullPath: '/negocio/aprovacoes'
      preLoaderRoute: typeof AuthenticatedNegocioAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/agenda': {
      id: '/_authenticated/negocio/agenda'
      path: '/negocio/agenda'
      fullPath: '/negocio/agenda'
      preLoaderRoute: typeof AuthenticatedNegocioAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/stock': {
      id: '/_authenticated/casa/stock'
      path: '/casa/stock'
      fullPath: '/casa/stock'
      preLoaderRoute: typeof AuthenticatedCasaStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/scanner': {
      id: '/_authenticated/casa/scanner'
      path: '/casa/scanner'
      fullPath: '/casa/scanner'
      preLoaderRoute: typeof AuthenticatedCasaScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/relatorios': {
      id: '/_authenticated/casa/relatorios'
      path: '/casa/relatorios'
      fullPath: '/casa/relatorios'
      preLoaderRoute: typeof AuthenticatedCasaRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/receitas': {
      id: '/_authenticated/casa/receitas'
      path: '/casa/receitas'
      fullPath: '/casa/receitas'
      preLoaderRoute: typeof AuthenticatedCasaReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/lista-compras': {
      id: '/_authenticated/casa/lista-compras'
      path: '/casa/lista-compras'
      fullPath: '/casa/lista-compras'
      preLoaderRoute: typeof AuthenticatedCasaListaComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/despesas': {
      id: '/_authenticated/casa/despesas'
      path: '/casa/despesas'
      fullPath: '/casa/despesas'
      preLoaderRoute: typeof AuthenticatedCasaDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEquipaRoute: typeof AuthenticatedEquipaRoute
  AuthenticatedCasaDespesasRoute: typeof AuthenticatedCasaDespesasRoute
  AuthenticatedCasaListaComprasRoute: typeof AuthenticatedCasaListaComprasRoute
  AuthenticatedCasaReceitasRoute: typeof AuthenticatedCasaReceitasRoute
  AuthenticatedCasaRelatoriosRoute: typeof AuthenticatedCasaRelatoriosRoute
  AuthenticatedCasaScannerRoute: typeof AuthenticatedCasaScannerRoute
  AuthenticatedCasaStockRoute: typeof AuthenticatedCasaStockRoute
  AuthenticatedNegocioAgendaRoute: typeof AuthenticatedNegocioAgendaRoute
  AuthenticatedNegocioAprovacoesRoute: typeof AuthenticatedNegocioAprovacoesRoute
  AuthenticatedNegocioClientesRoute: typeof AuthenticatedNegocioClientesRoute
  AuthenticatedNegocioDespesasRoute: typeof AuthenticatedNegocioDespesasRoute
  AuthenticatedNegocioEncomendasRoute: typeof AuthenticatedNegocioEncomendasRoute
  AuthenticatedNegocioRelatoriosRoute: typeof AuthenticatedNegocioRelatoriosRoute
  AuthenticatedNegocioStockRoute: typeof AuthenticatedNegocioStockRoute
  AuthenticatedNegocioVendasRoute: typeof AuthenticatedNegocioVendasRoute
  AuthenticatedCasaIndexRoute: typeof AuthenticatedCasaIndexRoute
  AuthenticatedNegocioIndexRoute: typeof AuthenticatedNegocioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEquipaRoute: AuthenticatedEquipaRoute,
  AuthenticatedCasaDespesasRoute: AuthenticatedCasaDespesasRoute,
  AuthenticatedCasaListaComprasRoute: AuthenticatedCasaListaComprasRoute,
  AuthenticatedCasaReceitasRoute: AuthenticatedCasaReceitasRoute,
  AuthenticatedCasaRelatoriosRoute: AuthenticatedCasaRelatoriosRoute,
  AuthenticatedCasaScannerRoute: AuthenticatedCasaScannerRoute,
  AuthenticatedCasaStockRoute: AuthenticatedCasaStockRoute,
  AuthenticatedNegocioAgendaRoute: AuthenticatedNegocioAgendaRoute,
  AuthenticatedNegocioAprovacoesRoute: AuthenticatedNegocioAprovacoesRoute,
  AuthenticatedNegocioClientesRoute: AuthenticatedNegocioClientesRoute,
  AuthenticatedNegocioDespesasRoute: AuthenticatedNegocioDespesasRoute,
  AuthenticatedNegocioEncomendasRoute: AuthenticatedNegocioEncomendasRoute,
  AuthenticatedNegocioRelatoriosRoute: AuthenticatedNegocioRelatoriosRoute,
  AuthenticatedNegocioStockRoute: AuthenticatedNegocioStockRoute,
  AuthenticatedNegocioVendasRoute: AuthenticatedNegocioVendasRoute,
  AuthenticatedCasaIndexRoute: AuthenticatedCasaIndexRoute,
  AuthenticatedNegocioIndexRoute: AuthenticatedNegocioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EncomendaTokenRoute: EncomendaTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
