/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEquipaRouteImport } from './routes/_authenticated/equipa'
import { Route as AuthenticatedNegocioIndexRouteImport } from './routes/_authenticated/negocio/index'
import { Route as AuthenticatedCasaIndexRouteImport } from './routes/_authenticated/casa/index'
import { Route as AuthenticatedNegocioVendasRouteImport } from './routes/_authenticated/negocio/vendas'
import { Route as AuthenticatedNegocioStockRouteImport } from './routes/_authenticated/negocio/stock'
import { Route as AuthenticatedNegocioDespesasRouteImport } from './routes/_authenticated/negocio/despesas'
import { Route as AuthenticatedNegocioClientesRouteImport } from './routes/_authenticated/negocio/clientes'
import { Route as AuthenticatedCasaStockRouteImport } from './routes/_authenticated/casa/stock'
import { Route as AuthenticatedCasaDespesasRouteImport } from './routes/_authenticated/casa/despesas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipaRoute = AuthenticatedEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegocioIndexRoute =
  AuthenticatedNegocioIndexRouteImport.update({
    id: '/negocio/',
    path: '/negocio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaIndexRoute = AuthenticatedCasaIndexRouteImport.update({
  id: '/casa/',
  path: '/casa/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegocioVendasRoute =
  AuthenticatedNegocioVendasRouteImport.update({
    id: '/negocio/vendas',
    path: '/negocio/vendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioStockRoute =
  AuthenticatedNegocioStockRouteImport.update({
    id: '/negocio/stock',
    path: '/negocio/stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioDespesasRoute =
  AuthenticatedNegocioDespesasRouteImport.update({
    id: '/negocio/despesas',
    path: '/negocio/despesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegocioClientesRoute =
  AuthenticatedNegocioClientesRouteImport.update({
    id: '/negocio/clientes',
    path: '/negocio/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasaStockRoute = AuthenticatedCasaStockRouteImport.update({
  id: '/casa/stock',
  path: '/casa/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasaDespesasRoute =
  AuthenticatedCasaDespesasRouteImport.update({
    id: '/casa/despesas',
    path: '/casa/despesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/casa/despesas': typeof AuthenticatedCasaDespesasRoute
  '/casa/stock': typeof AuthenticatedCasaStockRoute
  '/negocio/clientes': typeof AuthenticatedNegocioClientesRoute
  '/negocio/despesas': typeof AuthenticatedNegocioDespesasRoute
  '/negocio/stock': typeof AuthenticatedNegocioStockRoute
  '/negocio/vendas': typeof AuthenticatedNegocioVendasRoute
  '/casa/': typeof AuthenticatedCasaIndexRoute
  '/negocio/': typeof AuthenticatedNegocioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/equipa': typeof AuthenticatedEquipaRoute
  '/casa/despesas': typeof AuthenticatedCasaDespesasRoute
  '/casa/stock': typeof AuthenticatedCasaStockRoute
  '/negocio/clientes': typeof AuthenticatedNegocioClientesRoute
  '/negocio/despesas': typeof AuthenticatedNegocioDespesasRoute
  '/negocio/stock': typeof AuthenticatedNegocioStockRoute
  '/negocio/vendas': typeof AuthenticatedNegocioVendasRoute
  '/casa': typeof AuthenticatedCasaIndexRoute
  '/negocio': typeof AuthenticatedNegocioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/equipa': typeof AuthenticatedEquipaRoute
  '/_authenticated/casa/despesas': typeof AuthenticatedCasaDespesasRoute
  '/_authenticated/casa/stock': typeof AuthenticatedCasaStockRoute
  '/_authenticated/negocio/clientes': typeof AuthenticatedNegocioClientesRoute
  '/_authenticated/negocio/despesas': typeof AuthenticatedNegocioDespesasRoute
  '/_authenticated/negocio/stock': typeof AuthenticatedNegocioStockRoute
  '/_authenticated/negocio/vendas': typeof AuthenticatedNegocioVendasRoute
  '/_authenticated/casa/': typeof AuthenticatedCasaIndexRoute
  '/_authenticated/negocio/': typeof AuthenticatedNegocioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/equipa'
    | '/casa/despesas'
    | '/casa/stock'
    | '/negocio/clientes'
    | '/negocio/despesas'
    | '/negocio/stock'
    | '/negocio/vendas'
    | '/casa/'
    | '/negocio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/equipa'
    | '/casa/despesas'
    | '/casa/stock'
    | '/negocio/clientes'
    | '/negocio/despesas'
    | '/negocio/stock'
    | '/negocio/vendas'
    | '/casa'
    | '/negocio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/equipa'
    | '/_authenticated/casa/despesas'
    | '/_authenticated/casa/stock'
    | '/_authenticated/negocio/clientes'
    | '/_authenticated/negocio/despesas'
    | '/_authenticated/negocio/stock'
    | '/_authenticated/negocio/vendas'
    | '/_authenticated/casa/'
    | '/_authenticated/negocio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipa': {
      id: '/_authenticated/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof AuthenticatedEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/': {
      id: '/_authenticated/negocio/'
      path: '/negocio'
      fullPath: '/negocio/'
      preLoaderRoute: typeof AuthenticatedNegocioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/': {
      id: '/_authenticated/casa/'
      path: '/casa'
      fullPath: '/casa/'
      preLoaderRoute: typeof AuthenticatedCasaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/vendas': {
      id: '/_authenticated/negocio/vendas'
      path: '/negocio/vendas'
      fullPath: '/negocio/vendas'
      preLoaderRoute: typeof AuthenticatedNegocioVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/stock': {
      id: '/_authenticated/negocio/stock'
      path: '/negocio/stock'
      fullPath: '/negocio/stock'
      preLoaderRoute: typeof AuthenticatedNegocioStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/despesas': {
      id: '/_authenticated/negocio/despesas'
      path: '/negocio/despesas'
      fullPath: '/negocio/despesas'
      preLoaderRoute: typeof AuthenticatedNegocioDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio/clientes': {
      id: '/_authenticated/negocio/clientes'
      path: '/negocio/clientes'
      fullPath: '/negocio/clientes'
      preLoaderRoute: typeof AuthenticatedNegocioClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/stock': {
      id: '/_authenticated/casa/stock'
      path: '/casa/stock'
      fullPath: '/casa/stock'
      preLoaderRoute: typeof AuthenticatedCasaStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa/despesas': {
      id: '/_authenticated/casa/despesas'
      path: '/casa/despesas'
      fullPath: '/casa/despesas'
      preLoaderRoute: typeof AuthenticatedCasaDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEquipaRoute: typeof AuthenticatedEquipaRoute
  AuthenticatedCasaDespesasRoute: typeof AuthenticatedCasaDespesasRoute
  AuthenticatedCasaStockRoute: typeof AuthenticatedCasaStockRoute
  AuthenticatedNegocioClientesRoute: typeof AuthenticatedNegocioClientesRoute
  AuthenticatedNegocioDespesasRoute: typeof AuthenticatedNegocioDespesasRoute
  AuthenticatedNegocioStockRoute: typeof AuthenticatedNegocioStockRoute
  AuthenticatedNegocioVendasRoute: typeof AuthenticatedNegocioVendasRoute
  AuthenticatedCasaIndexRoute: typeof AuthenticatedCasaIndexRoute
  AuthenticatedNegocioIndexRoute: typeof AuthenticatedNegocioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEquipaRoute: AuthenticatedEquipaRoute,
  AuthenticatedCasaDespesasRoute: AuthenticatedCasaDespesasRoute,
  AuthenticatedCasaStockRoute: AuthenticatedCasaStockRoute,
  AuthenticatedNegocioClientesRoute: AuthenticatedNegocioClientesRoute,
  AuthenticatedNegocioDespesasRoute: AuthenticatedNegocioDespesasRoute,
  AuthenticatedNegocioStockRoute: AuthenticatedNegocioStockRoute,
  AuthenticatedNegocioVendasRoute: AuthenticatedNegocioVendasRoute,
  AuthenticatedCasaIndexRoute: AuthenticatedCasaIndexRoute,
  AuthenticatedNegocioIndexRoute: AuthenticatedNegocioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
